{
 "title": "Dashboard Traffic Simulator",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:00:00.014Z" },
 "panels": [
  {
   "title": "Ora di entrata, uscita e velocità media per ogni veicolo",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "simulation_db",
     "rawSql": "SELECT\r\n    plate AS vehicle,\r\n    TIME(spawn_datetime) AS time_start,\r\n    TIME(exit_datetime) AS time_end,\r\n    avg_speed\r\nFROM Vehicle\r\nORDER BY TIME(spawn_datetime);"
    }
   ]
  },
  {
   "title": "Tipologia Veicoli",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "simulation_db",
     "rawSql": "SELECT COUNT(id), type \r\nFROM simulation_db.Vehicle \r\nGROUP BY type;"
    }
   ]
  },
  {
   "title": "Numero di veicoli per ogni corsia",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "simulation_db",
     "rawSql": "SELECT id AS Source, n_vehicle AS Vehicle \r\nFROM simulation_db.Traffic_Light"
    }
   ]
  },
  {
   "title": "Numero di veicoli per ogni ora",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "simulation_db",
     "rawSql": "SELECT\r\n    HOUR(STR_TO_DATE(spawn_time, '%H:%i:%s')) AS hours_of_the_day,\r\n    COUNT(*) AS vehicle_count\r\nFROM\r\n    Vehicle\r\nGROUP BY\r\n    HOUR(STR_TO_DATE(spawn_time, '%H:%i:%s'))\r\nORDER BY\r\n    hours_of_the_day;"
    }
   ]
  },
  {
   "title": "Tempo medio attesa per ogni semaforo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  t.id AS traffic_light_id,\r\n  AVG(v.wait_time) AS avg_wait_time\r\nFROM Vehicle v\r\nINNER JOIN Traffic_Light t ON v.source = t.id\r\nGROUP BY traffic_light_id;"
    }
   ]
  },
  {
   "title": "Tempo medio nel sistema per ogni ora",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dataset": "simulation_db",
     "rawSql": "SELECT\r\n    HOUR(STR_TO_DATE(spawn_time, '%H:%i:%s')) AS hour_of_day,\r\n    AVG(system_time) AS avg_system_time\r\nFROM\r\n    Vehicle\r\nGROUP BY\r\n    HOUR(STR_TO_DATE(spawn_time, '%H:%i:%s'));"
    }
   ]
  },
  {
   "title": "Tempo medio attesa per ogni ora",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "simulation_db",
     "rawSql": "SELECT\r\n    HOUR(STR_TO_DATE(spawn_time, '%H:%i:%s')) AS hour_of_day,\r\n    AVG(wait_time) AS avg_wait_time\r\nFROM\r\n    Vehicle\r\nGROUP BY\r\n    HOUR(STR_TO_DATE(spawn_time, '%H:%i:%s'));\r\n"
    }
   ]
  }
 ]
}